name: Destroy

defaults:
  run:
    working-directory: ./terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Destroy infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.3

      - name: Terraform init
        run: terraform init

      - name: Terraform destroy
        run: |
          terraform destroy \
            -var "do_token=${{ secrets.DO_TOKEN }}" \
            -var "pvt_key=${{ secrets.DO_PRIVATE_KEY }}"
